fix: pipelines

diff --git a/.github/workflows/dev-deploy-auth.yml b/.github/workflows/dev-deploy-auth.yml
--- a/.github/workflows/dev-deploy-auth.yml
+++ b/.github/workflows/dev-deploy-auth.yml
@@ -42,12 +42,16 @@ jobs:
         run: |
           yq e '( .images[] | select(.name == strenv(IMAGE_NAME)) ).newTag = strenv(IMAGE_TAG)' -i $KUSTOMIZE_PATH
 
-      - name: Commit and push changes
+      - name: Commit and push with retry
         run: |
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
-          git fetch origin develop
-          git rebase origin/develop
+
           git add $KUSTOMIZE_PATH
           git commit -m "ci: update service-a image to $IMAGE_TAG" || echo "No changes to commit"
-          git push origin HEAD:develop
+
+          for i in {1..5}; do
+            git fetch origin develop
+            git rebase origin/develop || { echo "Rebase failed"; exit 1; }
+            git push origin HEAD:develop && break || sleep 5
+          done
